graph LR
A("Continuous<br/>Delivery")
B("<strong>Lean Management:</strong><br> Team Experimentation<br> Small Batches<br>
Implementing Feedback")
C("Westrum<br/>Organizational<br/>Culture")
D("Software<br/>Delivery<br/>Performance")
F("Organizational<br/>Performance")
A-->C
B-->C
C --> D("Software<br/>Delivery<br/>Performance")
C --> F("Organizational<br/>Performance")
