graph LR
OC("Westrum<br/>Organizational<br/>Culture")
JS("Job Satisfaction")
SD("Software<br/>Delivery<br/>Performance")
OP("Organizational<br/>Performance")
OC --> SD
SD --> OP
OC --> JS
OC --> OP
JS --> OP
